### ISSUE TITLE
What is this about sir

### ISSUE THREAD

**Issue by Mane-Olawale** [devhammed/reacting-to-php#1]
https://github.com/devhammed/reacting-to-php/blob/551006e5602e79b45c1f4419e79a0152bec3323f/src/AppServer.php#L23

**Comment by devhammed** [comment]
@Mane-Olawale This is using ReactPHP to create a PHP TCP server without relying on the traditional way where Apache/Nginx will be the one to send the request to PHP and return the response back.

You can check `public/index.php` for sample usage.
